import './globals.css';
import { Providers } from '$lib/components/Providers';

export const metadata = {
	title: 'Next.js App',
	description: 'Generated by Next.js',
	icons: {
		icon: '/favicon.svg'
	}
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
